
CREATE DATABASE task_manager;
USE task_manager;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(100),
 password VARCHAR(255),
 role VARCHAR(20)
);

CREATE TABLE tasks (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(100),
 status VARCHAR(50)
);
